# Generated by Django 5.2.7 on 2025-11-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created']},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created'], name='blogapp_com_created_22385d_idx'),
        ),
    ]
