# Generated by Django 5.2.7 on 2025-12-20 18:58

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_post_tags'),
    ]

    operations = [
        TrigramExtension()
    ]
